/* ============================================ */
/*  FITFORGE — Main Application                  */
/*  Products · Cart · Filters · Trends · Bot    */
/* ============================================ */
// =============================================
// PRODUCTS
// =============================================
var PRODUCTS = [
  {id:1,name:'Pro Resistance Bands Set',category:'gear',emoji:'\u{1F3CB}\u{FE0F}',price:34.99,originalPrice:null,badge:'trending',badgeText:'\u{1F525} Hot',image:'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop&q=80',desc:'5-level resistance bands with non-slip nylon. Perfect for home workouts, rehab, and strength training.',specs:['5 levels (10-50 lbs)','Non-slip design','Carry bag included','Door anchor included'],variantLabel:'Level',variants:['Light','Medium','Heavy','X-Heavy','Pro Set']},
  {id:2,name:'Smart Jump Rope',category:'gear',emoji:'\u23F3',price:49.99,originalPrice:69.99,badge:'sale',badgeText:'-28%',image:'https://images.unsplash.com/photo-1598714549948-9e8f2e3bcd47?w=400&h=400&fit=crop&q=80',desc:'Bluetooth-connected jump rope with real-time count, calories, and workout tracking.',specs:['Bluetooth 5.0','LED counter','Silicone grips','USB-C charging'],variantLabel:'Color',variants:['Black','Teal','Pink']},
  {id:3,name:'Organic Plant Protein',category:'supplements',emoji:'\u{1F964}',price:44.99,originalPrice:54.99,badge:'trending',badgeText:'\u{1F331} Vegan',image:'https://images.unsplash.com/photo-1622485830543-773c4abc3e4c?w=400&h=400&fit=crop&q=80',desc:'30g plant-based protein per serving. Pea, hemp, and brown rice blend.',specs:['30g protein/serving','5g BCAAs','No artificial sweeteners','Vanilla & Chocolate'],variantLabel:'Flavor',variants:['Vanilla','Chocolate','Strawberry','Unflavored']},
  {id:4,name:'Theragun Mini 2.0',category:'recovery',emoji:'\u{1F52B}',price:199.99,originalPrice:249.99,badge:'sale',badgeText:'Sale',image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&q=80',desc:'Ultra-portable percussion massage gun with 3 speeds and QuietForce technology.',specs:['3 speed settings','QuietForce Tech','USB-C charging','6h battery life'],variantLabel:'Model',variants:['Standard','Pro']},
  {id:5,name:'Hypoallergenic Yoga Mat',category:'gear',emoji:'\u{1F9D8}',price:59.99,originalPrice:null,badge:'new',badgeText:'New',image:'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop&q=80',desc:'6mm thick eco-friendly TPE yoga mat with alignment lines. Non-slip.',specs:['6mm thickness','Alignment lines','Antimicrobial','Eco-friendly TPE'],variantLabel:'Color',variants:['Ocean Blue','Charcoal','Lavender','Sage Green']},
  {id:6,name:'Hydration Electrolyte Pack',category:'supplements',emoji:'\u{1F4A7}',price:24.99,originalPrice:null,badge:null,badgeText:null,image:'https://images.unsplash.com/photo-1559305616-3f99cd43e353?w=400&h=400&fit=crop&q=80',desc:'Zero-sugar electrolyte packets with essential minerals. 12-pack.',specs:['Zero sugar','12 packets','500mg electrolytes','Vitamin C + Zinc'],variantLabel:'Flavor',variants:['Lemon Lime','Berry','Orange','Tropical']},
  {id:7,name:'Compression Recovery Boots',category:'recovery',emoji:'\u{1F9B5}',price:299.99,originalPrice:379.99,badge:'sale',badgeText:'Sale',image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=400&h=400&fit=crop&q=80',desc:'Full-leg air compression system for accelerated recovery.',specs:['4 massage modes','3 intensity levels','Full-leg coverage','Rechargeable'],variantLabel:'Size',variants:['S/M','L/XL']},
  {id:8,name:'8-Week HIIT Program (Digital)',category:'digital',emoji:'\u{1F4F1}',price:29.99,originalPrice:49.99,badge:'trending',badgeText:'Trending',image:'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=400&h=400&fit=crop&q=80',desc:'Progressive HIIT training program. Video demos, PDF workouts.',specs:['8 weeks','24 workouts','Video demos','PDF + tracking sheets'],variantLabel:'Level',variants:['Beginner','Intermediate','Advanced']},
  {id:9,name:'Seamless Gym Leggings',category:'apparel',emoji:'\u{1F456}',price:54.99,originalPrice:null,badge:'new',badgeText:'New',image:'https://images.unsplash.com/photo-1591946600619-1b0c6b0e7b0c?w=400&h=400&fit=crop&q=80',desc:'High-waist seamless compression leggings. Moisture-wicking, squat-proof.',specs:['High-waist','Squat-proof','Moisture-wicking','4-way stretch'],variantLabel:'Size',variants:['XS','S','M','L','XL']},
  {id:10,name:'Foam Roller Pro',category:'recovery',emoji:'\u{1F504}',price:39.99,originalPrice:null,badge:null,badgeText:null,image:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop&q=80',desc:'High-density foam roller with textured surface for deep tissue release.',specs:['18" length','High-density','Textured surface','Hollow core'],variantLabel:'Density',variants:['Standard','Firm','Extra Firm']},
  {id:11,name:'Meal Prep Planner (Digital)',category:'digital',emoji:'\u{1F957}',price:14.99,originalPrice:19.99,badge:'sale',badgeText:'Sale',image:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400&h=400&fit=crop&q=80',desc:'Done-for-you meal prep plans aligned with macro tracking.',specs:['12 weeks','Meal plans','Grocery lists','Macro tracking'],variantLabel:'Diet',variants:['Standard','Keto','Vegan','Paleo']},
  {id:12,name:'Quick-Dry Gym Towel Set',category:'apparel',emoji:'\u{1F9F4}',price:19.99,originalPrice:null,badge:null,badgeText:null,image:'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=400&fit=crop&q=80',desc:'Set of 3 microfibre gym towels. Quick-dry, antibacterial, compact.',specs:['Set of 3','Microfibre','Antibacterial','Compact fold'],variantLabel:'Color',variants:['Grey','Black','Navy']},
  {id:13,name:'Wrist & Ankle Weights Set',category:'gear',emoji:'\u{1F9B6}',price:27.99,originalPrice:null,badge:null,badgeText:null,image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=400&fit=crop&q=80',desc:'Adjustable 2lb each wrist/ankle weights. Sand-filled, neoprene.',specs:['2lb each','Adjustable','Neoprene','Sand-filled'],variantLabel:'Weight',variants:['1lb','2lb','3lb','5lb']},
  {id:14,name:'Mindfulness & Meditation Guide',category:'digital',emoji:'\u{1F9E0}',price:19.99,originalPrice:null,badge:'trending',badgeText:'Trending',image:'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=400&fit=crop&q=80',desc:'30-day guided meditation program. Audio tracks, journal prompts.',specs:['30 days','Audio tracks','Journal prompts','Breathwork exercises'],variantLabel:'Format',variants:['Audio Only','Audio + PDF']},
  {id:15,name:'Performance Tank Top',category:'apparel',emoji:'\u{1F455}',price:34.99,originalPrice:44.99,badge:'sale',badgeText:'Sale',image:'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&q=80',desc:'Lightweight, moisture-wicking tank top. Racerback design.',specs:['Moisture-wicking','Racerback','Flatlock seams','UPF 50+'],variantLabel:'Size',variants:['S','M','L','XL','XXL']}
];
function [continue]