/* ============================================ */
/*  FITFORGE — Main Application                  */
/*  Products · Cart · Filters · Trends · Bot    */
/* ============================================ */

const PRODUCTS = [
  { id: 1, name: 'Pro Resistance Bands Set', category: 'gear', emoji: '🏋️', price: 34.99, originalPrice: null, badge: 'trending', badgeText: '🔥 Hot', desc: '5-level resistance bands with non-slip nylon. Perfect for home workouts, rehab, and strength training.', specs: ['5 levels (10-50 lbs)', 'Non-slip design', 'Carry bag included', 'Door anchor included'], variantLabel: 'Level', variants: ['Light', 'Medium', 'Heavy', 'X-Heavy', 'Pro Set'] },
  { id: 2, name: 'Smart Jump Rope', category: 'gear', emoji: '⏳', price: 49.99, originalPrice: 69.99, badge: 'sale', badgeText: '-28%', desc: 'Bluetooth-connected jump rope with real-time count, calories, and workout tracking. Syncs with your phone.', specs: ['Bluetooth 5.0', 'LED counter', 'Silicone grips', 'USB-C charging'], variantLabel: 'Color', variants: ['Black', 'Teal', 'Pink'] },
  { id: 3, name: 'Organic Plant Protein', category: 'supplements', emoji: '🥤', price: 44.99, originalPrice: 54.99, badge: 'trending', badgeText: '🌱 Vegan', desc: '30g plant-based protein per serving. Pea, hemp, and brown rice blend. No artificial sweeteners.', specs: ['30g protein/serving', '5g BCAAs', 'No artificial sweeteners', 'Vanilla & Chocolate'], variantLabel: 'Flavor', variants: ['Vanilla', 'Chocolate', 'Strawberry', 'Unflavored'] },
  { id: 4, name: 'Theragun Mini 2.0', category: 'recovery', emoji: '🔫', price: 199.99, originalPrice: 249.99, badge: 'sale', badgeText: '⚡ Sale', desc: 'Ultra-portable percussion massage gun with 3 speeds and QuietForce technology. Post-workout recovery.', specs: ['3 speed settings', 'QuietForce Tech', 'USB-C charging', '6h battery life'], variantLabel: 'Model', variants: ['Standard', 'Pro'] },
  { id: 5, name: 'Hypoallergenic Yoga Mat', category: 'gear', emoji: '🧘', price: 59.99, originalPrice: null, badge: 'new', badgeText: 'New', desc: '6mm thick eco-friendly TPE yoga mat with alignment lines. Non-slip surface, antimicrobial, machine washable.', specs: ['6mm thickness', 'Alignment lines', 'Antimicrobial', 'Eco-friendly TPE'], variantLabel: 'Color', variants: ['Ocean Blue', 'Charcoal', 'Lavender', 'Sage Green'] },
  { id: 6, name: 'Hydration Electrolyte Pack', category: 'supplements', emoji: '💧', price: 24.99, originalPrice: null, badge: null, badgeText: null, desc: 'Zero-sugar electrolyte packets with essential minerals. 12-pack, drink mix. Optimal hydration for workouts.', specs: ['Zero sugar', '12 packets', '500mg electrolytes', 'Vitamin C + Zinc'], variantLabel: 'Flavor', variants: ['Lemon Lime', 'Berry', 'Orange', 'Tropical'] },
  { id: 7, name: 'Compression Recovery Boots', category: 'recovery', emoji: '🦵', price: 299.99, originalPrice: 379.99, badge: 'sale', badgeText: '🔥 Sale', desc: 'Full-leg air compression system for accelerated recovery. 4 modes, 3 intensities. Post-run or post-lift.', specs: ['4 massage modes', '3 intensity levels', 'Full-leg coverage', 'Rechargeable'], variantLabel: 'Size', variants: ['S/M', 'L/XL'] },
  { id: 8, name: '8-Week HIIT Program (Digital)', category: 'digital', emoji: '📱', price: 29.99, originalPrice: 49.99, badge: 'trending', badgeText: '📈 Trending', desc: 'Progressive HIIT training program. Video demos, PDF workouts, and tracking sheets. Instant delivery.', specs: ['8 weeks', '24 workouts', 'Video demos', 'PDF + tracking sheets'], variantLabel: 'Level', variants: ['Beginner', 'Intermediate', 'Advanced'] },
  { id: 9, name: 'Seamless Gym Leggings', category: 'apparel', emoji: '👖', price: 54.99, originalPrice: null, badge: 'new', badgeText: '✨ New', desc: 'High-waist seamless compression leggings. Moisture-wicking, squat-proof, 4-way stretch.', specs: ['High-waist', 'Squat-proof', 'Moisture-wicking', '4-way stretch'], variantLabel: 'Size', variants: ['XS', 'S', 'M', 'L', 'XL'] },
  { id: 10, name: 'Foam Roller Pro', category: 'recovery', emoji: '🔄', price: 39.99, originalPrice: null, badge: null, badgeText: null, desc: 'High-density foam roller with textured surface for deep tissue release. 18" length, hollow core.', specs: ['18" length', 'High-density', 'Textured surface', 'Hollow core'], variantLabel: 'Density', variants: ['Standard', 'Firm', 'Extra Firm'] },
  { id: 11, name: 'Meal Prep Planner (Digital)', category: 'digital', emoji: '🥗', price: 14.99, originalPrice: 19.99, badge: 'sale', badgeText: '⚡ Sale', desc: 'Done-for-you meal prep plans aligned with macro tracking. 12-week planner with grocery lists. Instant delivery.', specs: ['12 weeks', 'Meal plans', 'Grocery lists', 'Macro tracking'], variantLabel: 'Diet', variants: ['Standard', 'Keto', 'Vegan', 'Paleo'] },
  { id: 12, name: 'Quick-Dry Gym Towel Set', category: 'apparel', emoji: '🧴', price: 19.99, originalPrice: null, badge: null, badgeText: null, desc: 'Set of 3 microfibre gym towels. Quick-dry, antibacterial, compact. Fits in any gym bag.', specs: ['Set of 3', 'Microfibre', 'Antibacterial', 'Compact fold'], variantLabel: 'Color', variants: ['Grey', 'Black', 'Navy'] },
  { id: 13, name: 'Wrist & Ankle Weights Set', category: 'gear', emoji: '🦶', price: 27.99, originalPrice: null, badge: null, badgeText: null, desc: 'Adjustable 2lb each wrist/ankle weights. Sand-filled, comfortable neoprene. Walking, running, rehab.', specs: ['2lb each', 'Adjustable', 'Neoprene', 'Sand-filled'], variantLabel: 'Weight', variants: ['1lb', '2lb', '3lb', '5lb'] },
  { id: 14, name: 'Mindfulness & Meditation Guide', category: 'digital', emoji: '🧠', price: 19.99, originalPrice: null, badge: 'trending', badgeText: '🧘 Trending', desc: '30-day guided meditation program. Audio tracks, journal prompts, and breathwork exercises. Instant delivery.', specs: ['30 days', 'Audio tracks', 'Journal prompts', 'Breathwork exercises'], variantLabel: 'Format', variants: ['Audio Only', 'Audio + PDF'] },
  { id: 15, name: 'Performance Tank Top', category: 'apparel', emoji: '👕', price: 34.99, originalPrice: 44.99, badge: 'sale', badgeText: '💥 Sale', desc: 'Lightweight, moisture-wicking tank top. Racerback design, flatlock seams for chafe-free movement.', specs: ['Moisture-wicking', 'Racerback', 'Flatlock seams', 'UPF 50+'], variantLabel: 'Size', variants: ['S', 'M', 'L', 'XL', 'XXL'] }
];

const TRENDS = [
  { id: 1, icon: '🏋️', tag: 'Training', title: 'Hybrid Training is Taking Over', desc: 'The old "cardio vs. weights" debate is dead. Hybrid training blends strength, endurance, and mobility into one seamless program. Think CrossFit meets marathon training.', date: 'Jul 28, 2026', readTime: '4 min read' },
  { id: 2, icon: '🧠', tag: 'Wellness', title: 'Biohacking for the Everyday Athlete', desc: 'Cold plunges, red light therapy, and breathwork are no longer just for Silicon Valley.', date: 'Jul 25, 2026', readTime: '5 min read' },
  { id: 3, icon: '🌱', tag: 'Nutrition', title: 'Plant-Based Performance Gains', desc: 'More athletes are going plant-based without sacrificing gains. New pea and hemp protein blends rival whey.', date: 'Jul 22, 2026', readTime: '6 min read' },
  { id: 4, icon: '📱', tag: 'Tech', title: 'AI-Powered Workout Plans', desc: 'AI coaching apps are generating hyper-personalized workout plans that adapt in real-time.', date: 'Jul 19, 2026', readTime: '3 min read' },
  { id: 5, icon: '🧘', tag: 'Recovery', title: 'The Recovery Revolution', desc: 'Recovery isn\'t lazy — it\'s where the gains happen. Compression therapy, percussion massage, and sleep optimization.', date: 'Jul 16, 2026', readTime: '4 min read' },
  { id: 6, icon: '🔥', tag: 'Trending', title: '75-Day Challenges: Fad or Future?', desc: 'Structured transformation challenges are everywhere. We break down what works and what doesn\'t.', date: